### ISSUE TITLE
Compilation error: '_tc' was not declared in this scope

### ISSUE THREAD

**Issue by gc481** [pstolarz/Arduino-Temperature-Control-Library#10]
I'm working in OneWire compatibility mode on platformio, while compiling the code (below an extract of the full code) I obtain the error sequence "'_tc' was not declared in this scope"  in file OneWireNg_BitBang.cpp:112:9 and in file Platform_Delay.h:89:9. Any suggestion?
Thanks for helping.

======= CODE (REDUCED) =========

```

#include <OneWire.h>             
#include <DallasTemperature.h>  

...

#define ONE_WIRE_BUS      5                 // Data wire is plugged into port 5 on the ESP32
OneWire oneWire(ONE_WIRE_BUS);              // Setup a oneWire instance to communicate with any OneWire devices
DallasTemperature dsTempSensors(&oneWire);  // Pass our oneWire reference to Dallas Temperature.


void FireEvent_GetEnvData_Temperature() {
  PRINTSLN("\nGetEnvData_Temperature event fired!");
  //local variables
  float temp_water     = 0.0;
  float temp_out       = 0.0;
  dsTempSensors.requestTemperatures();

  if (blSwapThermometer==false) {
    PRINTSVLN(" Temp direct reading:",blSwapThermometer)
    iThermometerExt   = 0;
    iThermometerWater = 1;
  } else {
    PRINTSVLN(" Temp swapped reading:",blSwapThermometer)
    iThermometerExt   = 1;
    iThermometerWater = 0;
  }
  temp_out = dsTempSensors.getTempCByIndex(iThermometerExt);
  temp_water = dsTempSensors.getTempCByIndex(iThermometerWater);

....
}


void setup() {

dsTempSensors.begin();  //setup onewire + temp
timer.setInterval(  10000L, FireEvent_GetEnvData_Temperature);    
  

}

void loop() {

timer.run(); 
 

}


```

======= COMPILATION ERROR =========

```
...
Compiling .pio\build\esp32doit-devkit-v1\lib5af\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\platform\OneWireNg_ArduinoIdfESP32.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib5af\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\platform\OneWireNg_ArduinoIdfESP8266.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib5af\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\platform\Platform_Delay.cpp.o
In file included from .pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp:14:0:
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp: In member function 'virtual OneWireNg::ErrorCode OneWireNg_BitBang::reset()':
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp:112:9: note: in expansion of macro 'delayUs'
         delayUs(STD_RESET_LOW);
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp:115:9: note: in expansion of macro 'delayUs'
         delayUs(STD_RESET_SMPL);
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp:118:9: note: in expansion of macro 'delayUs'
         delayUs(STD_RESET_END);
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp: In member function 'virtual int OneWireNg_BitBang::touchBit(int, bool)':
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp:163:13: note: in expansion of macro 'delayUs'
             delayUs(STD_WRITE1_LOW);
             ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp:165:13: note: in expansion of macro 'delayUs'
             delayUs(STD_WRITE1_SMPL);
             ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp:169:13: note: in expansion of macro 'delayUs'
             delayUs(STD_WRITE1_END);
             ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp:175:13: note: in expansion of macro 'delayUs'
             delayUs(STD_WRITE0_LOW);
             ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\src\OneWireNg_BitBang.cpp:179:13: note: in expansion of macro 'delayUs'
             delayUs(STD_WRITE0_END);
             ^
Compiling .pio\build\esp32doit-devkit-v1\lib5af\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\platform\Platform_TimeCritical.cpp.o
*** [.pio\build\esp32doit-devkit-v1\lib5af\OneWireNg@src-e60c23af645de7aca9b3b37d492ea499\OneWireNg_BitBang.cpp.o] Error 1


```

**Comment by pstolarz** [comment]
Thanks for the catch. Use the latest commit on the OneWireNg master branch for the fix. Let me know about results.

**Comment by gc481** [comment]
I had already 0.11.1, forced update, no change
Platform.ini is

'''
[platformio]
default_envs = esp32doit-devkit-v1

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = 
	blynkkk/Blynk@^1.0.1
	paulstoffregen/Time@^1.6.1
	pstolarz/OneWireNg@^0.11.1
	https://github.com/pstolarz/Arduino-Temperature-Control-Library
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	simsso/ShiftRegister74HC595@^1.3.1
	https://github.com/Seeed-Studio/Grove_LED_Bar@^1.0.0
	ayushsharma82/AsyncElegantOTA@^2.2.6

'''
Compilation output is:

'''
Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html
PLATFORM: Espressif 32 (3.5.0) > DOIT ESP32 DEVKIT V1
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10006.210326 (1.0.6)
 - tool-esptoolpy 1.30100.210531 (3.1.0)
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 57 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Blynk> 1.0.1
|   |-- <WiFi> 1.0
|   |-- <Time> 1.6.1
|-- <Time> 1.6.1
**|-- <OneWireNg> 0.11.1
|-- <DallasTemperature> 3.9.1+sha.e3889aa
|   |-- <OneWireNg> 0.11.1**
|-- <LiquidCrystal_I2C> 1.1.4
|   |-- <Wire> 1.0.1
|-- <ShiftRegister74HC595> 1.3.1
|-- <Grove LED Bar> 1.0.0+sha.595b152
|-- <AsyncElegantOTA> 2.2.6
|   |-- <AsyncTCP> 1.1.1
|   |-- <ESP Async WebServer> 1.2.3
|   |   |-- <AsyncTCP> 1.1.1
|   |   |-- <FS> 1.0
|   |   |-- <WiFi> 1.0
|   |-- <FS> 1.0
|   |-- <Update> 1.0
|   |-- <WiFi> 1.0
|-- <AsyncTCP> 1.1.1
|-- <ESP Async WebServer> 1.2.3
|   |-- <AsyncTCP> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <SPI> 1.0
|-- <WiFi> 1.0
Building in release mode
Compiling .pio\build\esp32doit-devkit-v1\src\AQUABlynk.cpp.o
Generating partitions .pio\build\esp32doit-devkit-v1\partitions.bin
Compiling .pio\build\esp32doit-devkit-v1\lib6c2\WiFi\ETH.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib6c2\WiFi\WiFi.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib6c2\WiFi\WiFiAP.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib6c2\WiFi\WiFiClient.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib6c2\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib6c2\WiFi\WiFiMulti.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib6c2\WiFi\WiFiSTA.cpp.o
In file included from src/AQUABlynk.cpp:41:0:
.pio/libdeps/esp32doit-devkit-v1/AsyncElegantOTA/src/AsyncElegantOTA.h:4:2: warning: #warning AsyncElegantOTA.loop(); is deprecated, please remove it from loop() if defined. This function will be removed in a future release. [-Wcpp]
 #warning AsyncElegantOTA.loop(); is deprecated, please remove it from loop() if defined. This function will be removed in a future release.
  ^
Compiling .pio\build\esp32doit-devkit-v1\lib6c2\WiFi\WiFiScan.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib6c2\WiFi\WiFiServer.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib6c2\WiFi\WiFiUdp.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libd79\Time\DateStrings.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libd79\Time\Time.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libb04\Blynk\utility\BlynkDebug.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libb04\Blynk\utility\BlynkHandlers.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libb04\Blynk\utility\BlynkTimer.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libb04\Blynk\utility\utility.cpp.o
Archiving .pio\build\esp32doit-devkit-v1\libd79\libTime.a
Archiving .pio\build\esp32doit-devkit-v1\lib6c2\libWiFi.a
Compiling .pio\build\esp32doit-devkit-v1\lib864\OneWireNg\OneWireNg.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib864\OneWireNg\OneWireNg_BitBang.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib864\OneWireNg\drivers\DSTherm.cpp.o
Indexing .pio\build\esp32doit-devkit-v1\libd79\libTime.a
Indexing .pio\build\esp32doit-devkit-v1\lib6c2\libWiFi.a
Compiling .pio\build\esp32doit-devkit-v1\lib864\OneWireNg\platform\OneWireNg_ArduinoIdfESP32.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib864\OneWireNg\platform\OneWireNg_ArduinoIdfESP8266.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib864\OneWireNg\platform\Platform_Delay.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib864\OneWireNg\platform\Platform_TimeCritical.cpp.o
In file included from .pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp:14:0:
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp: In member function 'virtual OneWireNg::ErrorCode OneWireNg_BitBang::reset()':
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp:112:9: note: in expansion of macro 'delayUs'
         delayUs(STD_RESET_LOW);
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp:115:9: note: in expansion of macro 'delayUs'
         delayUs(STD_RESET_SMPL);
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp:118:9: note: in expansion of macro 'delayUs'
         delayUs(STD_RESET_END);
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp: In member function 'virtual int OneWireNg_BitBang::touchBit(int, bool)':
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp:163:13: note: in expansion of macro 'delayUs'
             delayUs(STD_WRITE1_LOW);
             ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp:165:13: note: in expansion of macro 'delayUs'
             delayUs(STD_WRITE1_SMPL);
             ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp:169:13: note: in expansion of macro 'delayUs'
             delayUs(STD_WRITE1_END);
             ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp:175:13: note: in expansion of macro 'delayUs'
             delayUs(STD_WRITE0_LOW);
             ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\platform/Platform_Delay.h:89:9: error: '_tc' was not declared in this scope
     if (_tc[xPortGetCoreID()].actv) { \
         ^
.pio\libdeps\esp32doit-devkit-v1\OneWireNg\src\OneWireNg_BitBang.cpp:179:13: note: in expansion of macro 'delayUs'
             delayUs(STD_WRITE0_END);
             ^
*** [.pio\build\esp32doit-devkit-v1\lib864\OneWireNg\OneWireNg_BitBang.cpp.o] Error 1
============================================================================================ [FAILED] Took 42.22 seconds ============================================================================================
The terminal process "C:\Users\crozzol5\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

'''

**Comment by pstolarz** [comment]
As I said, use master version instead of 0.11.1. In `platfrom.ini`. Replace
```
pstolarz/OneWireNg@^0.11.1
```
by
```
https://github.com/pstolarz/OneWireNg#master
```
Until new version 0.11.2 will be available with the fix incorporated.

**Comment by gc481** [comment]
Ops. Compilation ok.
Thanks a lot.
